In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [3]:
o_df=pd.read_excel("Online_Retail_Subset.xlsx",'Sheet1')

In [4]:
o_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
o_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,14999.0,7.464098,85.930115,-9360.0,1.00,2.00,7.00,2880.00
UnitPrice,14999.0,4.103366,20.106207,0.0,1.25,2.51,4.21,950.99
CustomerID,10728.0,15590.606264,1764.101280,12347.0,14213.00,15658.00,17218.00,18239.00

In [6]:
o_df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [7]:
o_df.shape

(14999, 8)

In [8]:
o_df.isna().sum()

InvoiceNo         0
StockCode         0
Description      60
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     4271
Country           0
dtype: int64

In [9]:
o_df["Description"].fillna(o_df['Description'].mode()[0],inplace=True)

In [10]:
o_df.isna().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     4271
Country           0
dtype: int64

In [11]:
o_df=o_df.dropna()

In [12]:
o_df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [13]:
o_df['Quantity'].where(o_df['Quantity']<0).count()

151

In [14]:
o_df["Quantity"]=o_df["Quantity"].abs()
o_df.describe()

           Quantity     UnitPrice    CustomerID
count  10728.000000  10728.000000  10728.000000
mean      11.440343      3.123054  15590.606264
std      101.147945      5.330112   1764.101280
min        1.000000      0.000000  12347.000000
25%        1.000000      1.250000  14213.000000
50%        4.000000      2.100000  15658.000000
75%       12.000000      3.750000  17218.000000
max     9360.000000    295.000000  18239.000000

In [15]:
o_df.replace(b,a,inplace=True)

NameError: name 'b' is not defined

In [16]:
o_df['Quantity'].where(o_df['Quantity']<0).count()

0

In [17]:
o_df['Quantity'].unique()

array([   6,    8,    2,   32,    3,    4,   24,   12,   48,   18,   20,
         36,   80,   64,   10,  120,   96,   23,    5,    1,   50,   40,
        100,  192,  432,  144,  288,   16,    9,  128,   25,   30,   28,
          7,   72,  200,  600,  480,   14,   11,   70,  252,   60,  216,
        384,   27,  108,   52, 9360,   75,  270,   42,  240,   90,  320,
         17, 1824,  204,   69,  160, 2880, 1400,   19,   39,   56,   13,
       1440,   15,  720,  156,  324,   41,  402,  378,  150,  300,   22,
         34], dtype=int64)

In [18]:
o_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,10728.0,11.440343,101.147945,1.0,1.00,4.0,12.00,9360.0
UnitPrice,10728.0,3.123054,5.330112,0.0,1.25,2.1,3.75,295.0
CustomerID,10728.0,15590.606264,1764.101280,12347.0,14213.00,15658.0,17218.00,18239.0

In [19]:
import re
o_df['InvoiceNo'].replace('C','',regex=True,inplace=True)
o_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
14969,537627,85049A,TRADITIONAL CHRISTMAS RIBBONS,24,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14970,537627,22086,PAPER CHAIN KIT 50'S CHRISTMAS,40,2010-12-07 14:58:00,2.55,14739.0,United Kingdom
14971,537627,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,40,2010-12-07 14:58:00,2.55,14739.0,United Kingdom
14972,537627,21187,WHITE BELL HONEYCOMB PAPER GARLAND,48,2010-12-07 14:58:00,1.45,14739.0,United Kingdom
14973,537627,21916,SET 12 RETRO WHITE CHALK STICKS,24,2010-12-07 14:58:00,0.42,14739.0,United Kingdom
14974,537627,21704,BAG 250g SWIRLY MARBLES,72,2010-12-07 14:58:00,0.72,14739.0,United Kingdom
14975,537627,85049C,ROMANTIC PINKS RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14976,537627,85049D,BRIGHT BLUES RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14977,537627,85049G,CHOCOLATE BOX RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14978,537627,21586,KINGS CHOICE GIANT TUBE MATCHES,48,2010-12-07 14:58:00,2.10,14739.0,United Kingdom
14979,537627,21587,COSY HOUR GIANT TUBE MATCHES,48,2010-12-07 14:58:00,2.10,14739.0,United Kingdom
14980,537627,22178,VICTORIAN GLASS HANGING T-LIGHT,96,2010-12-07 14:58:00,1.06,14739.0,United Kingdom
14981,537628,22149,FELTCRAFT 6 FLOWER FRIENDS,6,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14982,537628,20972,PINK CREAM FELT CRAFT TRINKET BOX,12,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14983,537628,21843,RED RETROSPOT CAKE STAND,1,2010-12-07 15:02:00,10.95,16293.0,United Kingdom
14984,537628,85066,CREAM SWEETHEART MINI CHEST,2,2010-12-07 15:02:00,12.75,16293.0,United Kingdom
14985,537628,21755,LOVE BUILDING BLOCK WORD,3,2010-12-07 15:02:00,5.95,16293.0,United Kingdom
14986,537628,22444,GROW YOUR OWN PLANT IN A CAN,24,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14987,537628,20682,RED RETROSPOT CHILDRENS UMBRELLA,6,2010-12-07 15:02:00,3.25,16293.0,United Kingdom
14988,537628,22299,PIG KEYRING WITH LIGHT & SOUND,24,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14989,537628,22834,HAND WARMER BABUSHKA DESIGN,24,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14990,537628,22867,HAND WARMER BIRD DESIGN,24,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14991,537628,21908,CHOCOLATE THIS WAY METAL SIGN,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14992,537628,21175,GIN + TONIC DIET METAL SIGN,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14993,537628,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-07 15:02:00,0.85,16293.0,United Kingdom
14994,537628,22804,CANDLEHOLDER PINK HANGING HEART,6,2010-12-07 15:02:00,2.95,16293.0,United Kingdom
14995,537628,72349B,SET/6 PURPLE BUTTERFLY T-LIGHTS,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14996,537628,72741,GRAND CHOCOLATECANDLE,9,2010-12-07 15:02:00,1.45,16293.0,United Kingdom
14997,537629,22762,CUPBOARD 3 DRAWER MA CAMPAGNE,1,2010-12-07 15:03:00,14.95,17419.0,United Kingdom
14998,537629,21773,DECORATIVE ROSE BATHROOM BOTTLE,12,2010-12-07 15:03:00,1.25,17419.0,United Kingdom

In [20]:
o_df['InvoiceNo'].where(o_df['InvoiceNo']=='C%').count()

0

In [21]:
import re
o_df['StockCode'].replace('[A-Z]','',regex=True,inplace=True)
o_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
20,536367,48187,DOORMAT NEW ENGLAND,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
24,536368,22914,BLUE COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
...,...,...,...,...,...,...,...,...
14969,537627,85049,TRADITIONAL CHRISTMAS RIBBONS,24,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14970,537627,22086,PAPER CHAIN KIT 50'S CHRISTMAS,40,2010-12-07 14:58:00,2.55,14739.0,United Kingdom
14971,537627,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,40,2010-12-07 14:58:00,2.55,14739.0,United Kingdom
14972,537627,21187,WHITE BELL HONEYCOMB PAPER GARLAND,48,2010-12-07 14:58:00,1.45,14739.0,United Kingdom
14973,537627,21916,SET 12 RETRO WHITE CHALK STICKS,24,2010-12-07 14:58:00,0.42,14739.0,United Kingdom
14974,537627,21704,BAG 250g SWIRLY MARBLES,72,2010-12-07 14:58:00,0.72,14739.0,United Kingdom
14975,537627,85049,ROMANTIC PINKS RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14976,537627,85049,BRIGHT BLUES RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14977,537627,85049,CHOCOLATE BOX RIBBONS,12,2010-12-07 14:58:00,1.25,14739.0,United Kingdom
14978,537627,21586,KINGS CHOICE GIANT TUBE MATCHES,48,2010-12-07 14:58:00,2.10,14739.0,United Kingdom
14979,537627,21587,COSY HOUR GIANT TUBE MATCHES,48,2010-12-07 14:58:00,2.10,14739.0,United Kingdom
14980,537627,22178,VICTORIAN GLASS HANGING T-LIGHT,96,2010-12-07 14:58:00,1.06,14739.0,United Kingdom
14981,537628,22149,FELTCRAFT 6 FLOWER FRIENDS,6,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14982,537628,20972,PINK CREAM FELT CRAFT TRINKET BOX,12,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14983,537628,21843,RED RETROSPOT CAKE STAND,1,2010-12-07 15:02:00,10.95,16293.0,United Kingdom
14984,537628,85066,CREAM SWEETHEART MINI CHEST,2,2010-12-07 15:02:00,12.75,16293.0,United Kingdom
14985,537628,21755,LOVE BUILDING BLOCK WORD,3,2010-12-07 15:02:00,5.95,16293.0,United Kingdom
14986,537628,22444,GROW YOUR OWN PLANT IN A CAN,24,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14987,537628,20682,RED RETROSPOT CHILDRENS UMBRELLA,6,2010-12-07 15:02:00,3.25,16293.0,United Kingdom
14988,537628,22299,PIG KEYRING WITH LIGHT & SOUND,24,2010-12-07 15:02:00,1.25,16293.0,United Kingdom
14989,537628,22834,HAND WARMER BABUSHKA DESIGN,24,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14990,537628,22867,HAND WARMER BIRD DESIGN,24,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14991,537628,21908,CHOCOLATE THIS WAY METAL SIGN,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14992,537628,21175,GIN + TONIC DIET METAL SIGN,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14993,537628,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-07 15:02:00,0.85,16293.0,United Kingdom
14994,537628,22804,CANDLEHOLDER PINK HANGING HEART,6,2010-12-07 15:02:00,2.95,16293.0,United Kingdom
14995,537628,72349,SET/6 PURPLE BUTTERFLY T-LIGHTS,12,2010-12-07 15:02:00,2.10,16293.0,United Kingdom
14996,537628,72741,GRAND CHOCOLATECANDLE,9,2010-12-07 15:02:00,1.45,16293.0,United Kingdom
14997,537629,22762,CUPBOARD 3 DRAWER MA CAMPAGNE,1,2010-12-07 15:03:00,14.95,17419.0,United Kingdom
14998,537629,21773,DECORATIVE ROSE BATHROOM BOTTLE,12,2010-12-07 15:03:00,1.25,17419.0,United Kingdom

In [22]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

In [23]:
label_encoder=LabelEncoder()
o_df["Description"]=label_encoder.fit_transform(o_df['Description'])
o_df["Country"]=label_encoder.fit_transform(o_df["Country"])

In [30]:
b=o_df.drop(columns='InvoiceDate')

In [32]:
scaler=MinMaxScaler()
scaled_val=scaler.fit_transform(b)
scaled_val=pd.DataFrame(scaled_val,columns=o_df.columns)
o_df.head()

ValueError: could not convert string to float:

In [26]:
o_df['Total']=o_df['UnitPrice']*o_df['Quantity']

In [27]:
o_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total
0,536365,85123,1793,6,2010-12-01 08:26:00,2.55,17850.0,15,15.30
1,536365,71053,1796,6,2010-12-01 08:26:00,3.39,17850.0,15,20.34
2,536365,84406,479,8,2010-12-01 08:26:00,2.75,17850.0,15,22.00
3,536365,84029,907,6,2010-12-01 08:26:00,3.39,17850.0,15,20.34
4,536365,84029,1351,6,2010-12-01 08:26:00,3.39,17850.0,15,20.34